version: '3.3'
services:
  fastfood_frontend:
    build: ./fastfood_frontend
    container_name: fastfood_frontend
    ports:
      - 4200:4200
    depends_on:
      - fastfood_backend
  
  fastfood_backend:
    build: ./fastfood_backend
    container_name: fastfood_backend
    ports:
      - 8094:8094
