version: '3.3'
services:
  server:
    image: ubuntu:20.04
    container_name: server
    tty: true
    stdin_open: true
    depends_on:
      - mongo
      - postgres
      - redis
    command: bash
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: my-database
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: my-db
      POSTGRES_USER: my-user
      POSTGRES_PASSWORD: my-pass
