version: '3.3'
services:
  fastfood_frontend:
    build: ./fastfood_frontend
    container_name: fastfood_frontend
    ports:
      - 4200:4200
    networks:
      - front-tier
      - back-tier
  
  fastfood_backend:
    build: ./fastfood_backend
    container_name: fastfood_backend
    ports:
      - 8094:8094
    networks:
      - back-tier
networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}